# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SwiftMarkdown' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftMarkdown

  target 'SwiftMarkdownTests' do
    inherit! :search_paths
    
    pod 'Quick'
    pod 'Nimble'
    pod 'Nimble-Snapshots'
  end
end
